### ISSUE TITLE
Nullish coalescing operator (??) causing webpack build to fail

### ISSUE THREAD

**Issue by evanwills** [mswjs/headers-polyfill#59] opened 2023-08-28 12:52 UTC
Recent commit "feat: implements "getSetCookie" method on Headers" (https://github.com/mswjs/headers-polyfill/commit/cff8faf4f92ba8cfc0e62d000ecde4eb78a0a491)

changed line 74 of src/headers.ts (https://github.com/mswjs/headers-polyfill/blob/main/src/Headers.ts#L73)
from: 
```ts
get(name: string): string | null {
  return this[NORMALIZED_HEADERS][normalizeHeaderName(name)] || null
}
```
to
```ts
get(name: string): string | null {
  return this[NORMALIZED_HEADERS][normalizeHeaderName(name)] ?? null
}
```
(now using the [Nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing))

This is now causing webpack to throw a build error.

```
 ERROR  Failed to compile with 1 error9:19:13 pm

 error  in ./node_modules/headers-polyfill/lib/index.mjs

Module parse failed: Unexpected token (71:64)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|   get(name) {
>     return this[NORMALIZED_HEADERS][normalizeHeaderName(name)] ?? null;
|   }
|   set(name, value) {

 @ ./node_modules/msw/lib/index.js 147:30-57 304:31-58 542:31-58 549:31-58 574:31-58 927:31-58 1002:31-58 1005:31-58 1610:31-58
 @ ./src/mocks/browser.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
```

I've created a [repo](https://github.com/evanwills/msw-header-pollyfill--webpack-error/) to make it easy to reproduce the issue. 

I've also created a shell script ([`show-error.sh`](https://github.com/evanwills/msw-header-pollyfill--webpack-error/blob/master/show-error.sh)) to quickly show the error and what happens when you revert the change from to the `??` operator.

**Comment by kettanaito** [comment] 2023-08-28 13:08
Hey, @evanwills. Thanks for reporting this. This appears to be a duplicate of #58. I will close it so we could discuss/address it in that issue. Thanks.

**Closed by kettanaito** 2023-08-28 13:08 UTC
